name: app_transtunja
description: "Aplicación administrativa TransTunja"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.1

  # opción para tu rama actual 6.x
  flutter_map_cancellable_tile_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/