// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQPYZDtsbaXh3fehvalrKoHdBnGsxPpQ',
    appId: '1:290956858498:web:043bcd038aacc25bc0109b',
    messagingSenderId: '290956858498',
    projectId: 'fisica-f4672',
    authDomain: 'fisica-f4672.firebaseapp.com',
    storageBucket: 'fisica-f4672.firebasestorage.app',
    measurementId: 'G-DVV2R06B87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLYw9lLbIcI_-PKfd03p2rY379FUKIP0',
    appId: '1:290956858498:android:73f11339e3432eb4c0109b',
    messagingSenderId: '290956858498',
    projectId: 'fisica-f4672',
    storageBucket: 'fisica-f4672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8MUXxa0WEgelLZ8xo6j7rFOhe-TioKmI',
    appId: '1:290956858498:ios:b7e42453e579d9cdc0109b',
    messagingSenderId: '290956858498',
    projectId: 'fisica-f4672',
    storageBucket: 'fisica-f4672.firebasestorage.app',
    iosBundleId: 'com.transtunja.transtunja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8MUXxa0WEgelLZ8xo6j7rFOhe-TioKmI',
    appId: '1:290956858498:ios:b7e42453e579d9cdc0109b',
    messagingSenderId: '290956858498',
    projectId: 'fisica-f4672',
    storageBucket: 'fisica-f4672.firebasestorage.app',
    iosBundleId: 'com.transtunja.transtunja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBysjhf0O0-U6nC0PQC5NttzMI34YIu-Vk',
    appId: '1:290956858498:web:977f260a93f65805c0109b',
    messagingSenderId: '290956858498',
    projectId: 'fisica-f4672',
    authDomain: 'fisica-f4672.firebaseapp.com',
    storageBucket: 'fisica-f4672.firebasestorage.app',
    measurementId: 'G-EKYV9MFGCX',
  );
}
